### ISSUE TITLE
Failed to place message on internal cns queue

### ISSUE THREAD

**Issue by yeiniel** [Comcast/cmb#33]
I'm having problems with a topic that publish into a queue on the same server. Did you have test this to work. I create a new user and for this user a new topic and queue. Then a new subscription to the topic using the Queue ARN and tried both types: (SQS and CQS). All this has been done using webui. In both cases the response is "Failed to place message on internal cns queue". Is this a problem with the server configuration maybe?

**Comment by boriwo** [comment]
Yes this is tested and working. The correct protocol to subscribe a CQS queue is CQS (not SQS). Otherwise it sounds like you are doing all the right things.

Find some more details on common pitfalls here:

https://github.com/Comcast/cmb/blob/master/FAQ.txt

Generally the strategy should be to confirm that CQS is working first, and then try to get CNS to work (because CNS builds on top of CQS and thus without CQS there is no CNS).

My suspicion is that you have some more basic problem with CMB in general - maybe you see a Redis or Cassandra error in your CMB logs?

**Comment by yeiniel** [comment]
Yes. in the end i notice it can't connect to cassandra due to permission problems running the cassandra server.
